### ISSUE TITLE
Activiteit aanmaken heeft tijdvelden ipv tekst voor 'Aantal deelnemers' en 'Plaats'

### ISSUE THREAD

**Issue by kims72** [MarkHooijkaas/wikivents#31]
![screen shot 2015-09-17 at 00 11 25](https://cloud.githubusercontent.com/assets/104729/9919994/ef8f4cac-5cd0-11e5-9adb-665de4a74ff9.png)

**Comment by MarkHooijkaas** [comment]
is gefixed... bij handlebars onthoudt ie oude parameters
