### ISSUE TITLE
event en thema een herkenbare url geven

### ISSUE THREAD

**Issue by MarkHooijkaas** [MarkHooijkaas/wikivents#50]
Het zou mooi zijn als je makkelijk een link kan door sturen naar een thema.

**Comment by kims72** [comment]
Bijvoorbeeld: https://www.wikivents.nl/event/liftwedstrijd-groningen-utrecht-19-10-2015
Een tweede op dezelfde dag (heeeeeel onwaarschijnlijk) krijgt een volgnummer:
Bijvoorbeeld: https://www.wikivents.nl/event/liftwedstrijd-groningen-utrecht-19-10-2015-2
Bijvoorbeeld: https://www.wikivents.nl/event/liftwedstrijd-groningen-utrecht-19-10-2015-3

**Comment by MarkHooijkaas** [comment]
Nog iets mooier zou zijn:
https://www.wikivents.nl/event/2015/10/19/liftwedstrijd-groningen-utrecht
Dan zou je met een mooie url ook alle events van een jaar, maand of dag kunnen opvragen. 
Vergt nog wel wat slimmigheid bij het verwerken van url's maar is wel te doen.

**Comment by MarkHooijkaas** [comment]
Belangrijker is wat er gebeurt als de datum van een event wijzigt. Dan zouden oude url's niet meer werken. Dit geldt ook voor de naam van de event, maar daarvoor heb ik nog iets dat de oorspronkelijke url onthouden wordt, en gebruikt blijft, ook al is de event hernoemd. Alleen bij de datum lijkt die strategie minder wenselijk... maar datum verplaatsen maakt het ook wel een beetje een ander event.
